#!/bin/bash
set -e

read -rp "Enter commit message: " cmt_msg

# Remove trailing single or double quotes from message
cmt_msg="${cmt_msg//[\"\']/}"

# Validate commit message
if [[ -z "$cmt_msg" ]]; then
	echo "commit message cannot be empty :(. Aborting..."
	exit 1
fi

# Execute git commands
git add .
git commit -m "(AB) $cmt_msg"

echo "commit successfully created..."
echo "run the command 'git push' to finalise the operation."

